name: Crawl on Push and Schedule

on:
  push:
    branches: [ main ]
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '20 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 scrapy
        pip uninstall --yes pyOpenSSL
        pip install pyOpenSSL==22.0.0
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Crawl
      run: |
        scrapy crawl gpu -O data/nvidia.csv
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
